// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuVm7f6HmdsXhrhTad5-fXoh6W-4ioX2Q',
    appId: '1:889741314744:web:b9bd1f5393f7baa58f824d',
    messagingSenderId: '889741314744',
    projectId: 'auctionhub-eb094',
    authDomain: 'auctionhub-eb094.firebaseapp.com',
    storageBucket: 'auctionhub-eb094.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmk3lYYpfA13HBQIJbeNxnCVtsVq2q0Bo',
    appId: '1:889741314744:android:a5bbb020866299038f824d',
    messagingSenderId: '889741314744',
    projectId: 'auctionhub-eb094',
    storageBucket: 'auctionhub-eb094.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxvyUVsd57fdifTS_TyNQjXrNHlkCJRBw',
    appId: '1:889741314744:ios:7dca8842cbb0d7418f824d',
    messagingSenderId: '889741314744',
    projectId: 'auctionhub-eb094',
    storageBucket: 'auctionhub-eb094.firebasestorage.app',
    iosBundleId: 'com.example.auctionHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxvyUVsd57fdifTS_TyNQjXrNHlkCJRBw',
    appId: '1:889741314744:ios:7dca8842cbb0d7418f824d',
    messagingSenderId: '889741314744',
    projectId: 'auctionhub-eb094',
    storageBucket: 'auctionhub-eb094.firebasestorage.app',
    iosBundleId: 'com.example.auctionHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuVm7f6HmdsXhrhTad5-fXoh6W-4ioX2Q',
    appId: '1:889741314744:web:18eb986a51c8089f8f824d',
    messagingSenderId: '889741314744',
    projectId: 'auctionhub-eb094',
    authDomain: 'auctionhub-eb094.firebaseapp.com',
    storageBucket: 'auctionhub-eb094.firebasestorage.app',
  );
}
